name: Deploy CD

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:  # Para disparo manual

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Passo de Instalação do kubelogin
    - name: Install kubelogin
      run: |
        curl -LO https://github.com/Azure/kubelogin/releases/download/v0.1.3/kubelogin-linux-amd64.zip
        unzip kubelogin-linux-amd64.zip
        cd bin
        cd linux_amd64
        sudo install -o root -g root -m 0755 kubelogin /usr/local/bin/kubelogin
        pwd
    
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
          az storage -h
     