name: Deploy CD

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:  # Para disparo manual

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Passo de Instalação do kubelogin
    - name: Install kubelogin
      run: |
        curl -LO https://github.com/Azure/kubelogin/releases/download/v0.1.3/kubelogin-linux-amd64.zip
        pwd
        unzip kubelogin-linux-amd64.zip
        pwd
        ls -la
        pwd
        cd bin
        pwd
        ls -la
        cd linux_amd64
        pwd
        ls -la
        sudo install -o root -g root -m 0755 kubelogin /usr/local/bin/kubelogin
        pwd


    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS}}

