name: Check Run Example

on:
  check_run:
    types: [completed]

jobs:
  process_check_run:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event Information
        run: |
          echo "Event name: $GITHUB_EVENT_NAME"
          echo "Event payload: $GITHUB_EVENT_PATH"
      
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Check Run Details
        run: |
          echo "Check run ID: $GITHUB_RUN_ID"
          echo "Check run conclusion: $GITHUB_CHECK_RUN_CONCLUSION"
          echo "Check run name: $GITHUB_CHECK_RUN_NAME"
          echo "Check run status: $GITHUB_CHECK_RUN_STATUS"
          echo "Check run head SHA: $GITHUB_SHA"
          echo "Check run repository: $GITHUB_REPOSITORY"
